--- # docker-compose
name: A tool for defining and running multi-container Docker applications.
strategies:
    docker:
        image: docker/compose:{{.Version}}
        docker_conn: true
        mount_pwd: true
        versions:
          - version: 1.8.0
          - version: 1.7.1
    binary:
        base_url: https://github.com/docker/compose/releases/download/{{.Version}}/docker-compose-{{.MappedArch}}
        arch_map:
            windows_amd64: Windows-x86_64.exe
            linux_amd64: Linux-x86_64
            darwin_amd64: Darwin-x86_64
        versions:
          - version: 1.8.0
          - version: 1.7.1
...
